version: '3.7'


services:
    
  db:
    container_name: test_db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
    
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3


  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  app:
    container_name: Ylab_app
    build:
      context: .
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    command: "pytest tests/test_submenu_and_dish_count_in_menu.py -vv"
    
    ports:
      - 9999:8000
    depends_on:
      - db
      - adminer


      



