version: '3.1'

services:

  db:
    build:
        context: ./Docker
        dockerfile: db.Dockerfile
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menu_db
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
